import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Installation',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'doc', id: 'capstone/Installation/HYPRONET_INSTALLATION_GUIDE'},
        {type: 'doc', id: 'capstone/Installation/STARTUP_GUIDE'},
      ],
    },
    {
      type: 'category',
      label: 'User Manual',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Interface Overview',
          link: {type: 'generated-index', title: 'Interface Overview'},
          collapsible: true,
          collapsed: false,
          items: [
            {type: 'doc', id: 'capstone/UserGuide/interface-overview', label: 'Overview'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/model'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/materials'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/economic'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/calc-type'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/analysis'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/set-run'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/run'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/run-result'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/multi-tp'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/tp-analysis'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/system'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/display'},
            {type: 'doc', id: 'capstone/UserGuide/primary-menus/help'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'CodeExplanation',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'doc', id: 'capstone/CodeExplanation/CODE_EXPLANATION_GUIDELINES'},
        {type: 'doc', id: 'capstone/CodeExplanation/ai-codeexplanation-maintenance-workflow'},
        {type: 'doc', id: 'capstone/CodeExplanation/code-explanation-index'},
        {type: 'doc', id: 'capstone/CodeExplanation/code-explanation-overview'},
        {type: 'doc', id: 'capstone/CodeExplanation/dashboard-and-canvas'},
        {type: 'doc', id: 'capstone/CodeExplanation/time-period-and-economic-flow'},
        {type: 'doc', id: 'capstone/CodeExplanation/run-config-and-computation-start'},
        {type: 'doc', id: 'capstone/CodeExplanation/equation-writing-module'},
        {type: 'doc', id: 'capstone/CodeExplanation/plant-measurements-and-instrument-mapping'},
        {type: 'doc', id: 'capstone/CodeExplanation/save-diagram-and-node-cache'},
        {type: 'doc', id: 'capstone/CodeExplanation/custom-edge-and-stream-selection'},
        {type: 'doc', id: 'capstone/CodeExplanation/node-modal-and-variable-inputs'},
        {type: 'doc', id: 'capstone/CodeExplanation/shape-node-and-ports'},
        {type: 'doc', id: 'capstone/CodeExplanation/subnetwork-blueprint-and-instance-flow'},
        {type: 'doc', id: 'capstone/CodeExplanation/backend-data-routes-and-persistence'},
        {type: 'doc', id: 'capstone/CodeExplanation/compute-solver-callback-and-results'},
        {type: 'doc', id: 'capstone/CodeExplanation/translation-and-reverse-translation'},
        {type: 'doc', id: 'capstone/CodeExplanation/excel-import-pipeline'},
        {type: 'doc', id: 'capstone/CodeExplanation/alertsSlice'},
        {type: 'doc', id: 'capstone/CodeExplanation/authentication'},
        {type: 'doc', id: 'capstone/CodeExplanation/calc-type-flow'},
        {type: 'doc', id: 'capstone/CodeExplanation/calcTypeSlice'},
        {type: 'doc', id: 'capstone/CodeExplanation/canvasSlice'},
        {type: 'doc', id: 'capstone/CodeExplanation/computation-result'},
        {type: 'doc', id: 'capstone/CodeExplanation/custom-edge'},
        {type: 'doc', id: 'capstone/CodeExplanation/dashboard'},
        {type: 'doc', id: 'capstone/CodeExplanation/domainSlice'},
        {type: 'doc', id: 'capstone/CodeExplanation/global-tp'},
        {type: 'doc', id: 'capstone/CodeExplanation/header-bar'},
        {type: 'doc', id: 'capstone/CodeExplanation/human-input-flag'},
        {type: 'doc', id: 'capstone/CodeExplanation/modal'},
        {type: 'doc', id: 'capstone/CodeExplanation/nodeCacheSlice'},
        {type: 'doc', id: 'capstone/CodeExplanation/portVariableDataLogic'},
        {type: 'doc', id: 'capstone/CodeExplanation/run-history-and-results'},
        {type: 'doc', id: 'capstone/CodeExplanation/save-diagram'},
        {type: 'doc', id: 'capstone/CodeExplanation/savedSlice'},
        {type: 'doc', id: 'capstone/CodeExplanation/subnetwork-blueprint'},
        {type: 'doc', id: 'capstone/CodeExplanation/test'},
        {type: 'doc', id: 'capstone/CodeExplanation/timePeriodViewer'},
        {type: 'doc', id: 'capstone/CodeExplanation/tp-duration-base-and-solve-request'},
        {type: 'doc', id: 'capstone/CodeExplanation/tp-specs-panel'},
        {type: 'doc', id: 'capstone/CodeExplanation/tpChanges'},
      ],
    },
  ],
};

export default sidebars;
