import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {"type":"doc","id":"capstone/UserGuide/primary-menus/economic","label":"1. Economic Configuration and User Tables","className":"presentation-sidebar-item"},
    {"type":"doc","id":"capstone/UserGuide/primary-menus/analysis/plant-measurements","label":"2. Plant Measurement","className":"presentation-sidebar-item"},
    {"type":"doc","id":"capstone/UserGuide/primary-menus/model/extract-selection","label":"3. Extract Selection and Connection Names","className":"presentation-sidebar-item"},
    {"type":"doc","id":"capstone/UserGuide/primary-menus/run/computation-panel","label":"4. Calculation Progress and Result Processing","className":"presentation-sidebar-item"},
    {"type":"doc","id":"capstone/UserGuide/primary-menus/model/component-split-fractions","label":"5. Component Templates, Split Fractions and Excel Rules","className":"presentation-sidebar-item"},
    {"type":"doc","id":"capstone/CodeExplanation/large-model-performance-and-recovery","label":"6. Large-Model Performance","className":"presentation-sidebar-item"},
    {"type":"doc","id":"capstone/CodeExplanation/documentation-sync-and-publishing","label":"7. Documentation and Automated Publishing","className":"presentation-sidebar-item"},
    {type: 'autogenerated', dirName: 'capstone'},
  ],
};

export default sidebars;
